const IMG_URL =
  "https://raw.githubusercontent.com/saramff/face-recognition-images/refs/heads/master/objects/";

export const correctObjects = [
  {
    sentence: "has a piggy bank.",
    img: `${IMG_URL}piggy bank.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has a trash can.",
    img: `${IMG_URL}trash can.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has a rope.",
    img: `${IMG_URL}rope.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has a key.",
    img: `${IMG_URL}key.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has an umbrella.",
    img: `${IMG_URL}umbrella.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has glasses.",
    img: `${IMG_URL}glasses.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has a banana.",
    img: `${IMG_URL}banana.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has a calculator.",
    img: `${IMG_URL}calculator.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has scissors.",
    img: `${IMG_URL}scissors.jpg`,
    correct_response: "a",
  },
  {
    sentence: "has a hairbrush.",
    img: `${IMG_URL}hairbrush.jpg`,
    correct_response: "a",
  },
];

/*
  { sentence: "has a magnifying glass.", img: `${IMG_URL}magnifying-glass.jpg`, correct_response: "a" },
  { sentence: "has a guitar.", img: `${IMG_URL}guitar.jpg`, correct_response: "a" },
  { sentence: "has honey.", img: `${IMG_URL}honey.jpg`, correct_response: "a" },
  { sentence: "has a microphone.", img: `${IMG_URL}microphone.jpg`, correct_response: "a" },
  { sentence: "has a hammer.", img: `${IMG_URL}hammer.jpg`, correct_response: "a" },
  { sentence: "has milk.", img: `${IMG_URL}milk.jpg`, correct_response: "a" },
  { sentence: "has an egg.", img: `${IMG_URL}egg.jpg`, correct_response: "a" },
  { sentence: "has a dog.", img: `${IMG_URL}dog.jpg`, correct_response: "a" },
  { sentence: "has an orange.", img: `${IMG_URL}orange.jpg`, correct_response: "a" },
  { sentence: "has bread.", img: `${IMG_URL}bread.jpg`, correct_response: "a" },
  { sentence: "has a bicycle.", img: `${IMG_URL}bicycle.jpg`, correct_response: "a" },
  { sentence: "has coffee.", img: `${IMG_URL}coffee.jpg`, correct_response: "a" },
  { sentence: "has a balloon.", img: `${IMG_URL}balloon.jpg`, correct_response: "a" },
  { sentence: "has a pizza.", img: `${IMG_URL}pizza.jpg`, correct_response: "a" },
  { sentence: "has a pineapple.", img: `${IMG_URL}pineapple.jpg`, correct_response: "a" },
  { sentence: "has a computer.", img: `${IMG_URL}computer.jpg`, correct_response: "a" },
  { sentence: "has a ball.", img: `${IMG_URL}ball.jpg`, correct_response: "a" },
  { sentence: "has a butterfly.", img: `${IMG_URL}butterfly.jpg`, correct_response: "a" },
  { sentence: "has chocolate.", img: `${IMG_URL}chocolate.jpg`, correct_response: "a" },
  { sentence: "has a coin.", img: `${IMG_URL}coin.jpg`, correct_response: "a" },
  { sentence: "has a pencil.", img: `${IMG_URL}pencil.jpg`, correct_response: "a" },
  { sentence: "has a chair.", img: `${IMG_URL}chair.jpg`, correct_response: "a" },
  { sentence: "has a belt.", img: `${IMG_URL}belt.jpg`, correct_response: "a" },
  { sentence: "has a spoon.", img: `${IMG_URL}spoon.jpg`, correct_response: "a" },
  { sentence: "has a hat.", img: `${IMG_URL}hat.jpg`, correct_response: "a" },
  { sentence: "has cheese.", img: `${IMG_URL}cheese.jpg`, correct_response: "a" },
  { sentence: "has a flowerpot.", img: `${IMG_URL}flowerpot.jpg`, correct_response: "a" },
  { sentence: "has a milkshake.", img: `${IMG_URL}milkshake.jpg`, correct_response: "a" },
  { sentence: "has a flower.", img: `${IMG_URL}flower.jpg`, correct_response: "a" },
  { sentence: "has a watch.", img: `${IMG_URL}watch.jpg`, correct_response: "a" },
  { sentence: "has a tomato.", img: `${IMG_URL}tomato.jpg`, correct_response: "a" },
  { sentence: "has a pumpkin.", img: `${IMG_URL}pumpkin.jpg`, correct_response: "a" },
  { sentence: "has a dice.", img: `${IMG_URL}dice.jpg`, correct_response: "a" },
  { sentence: "has a watering can.", img: `${IMG_URL}watering-can.jpg`, correct_response: "a" },
  { sentence: "has a notebook.", img: `${IMG_URL}notebook.jpg`, correct_response: "a" },
  { sentence: "has an apple.", img: `${IMG_URL}apple.jpg`, correct_response: "a" },
  { sentence: "has a ruler.", img: `${IMG_URL}ruler.jpg`, correct_response: "a" },
];

*/

export const incorrectObjects = [
  "has a lamp.",
  "has a rug.",
  "has a fridge.",
  "has a frying pan.",
  "has a pillow.",
  "has a cage.",
  "has a ladder.",
  "has a cane.",
  "has a bottle.",
  "has a fan.",
  "has a suitcase.",
  "has a printer.",
  "has a wallet.",
  "has a flashlight.",
  "has a tie.",
  "has an iron.",
  "has a helmet.",
  "has a backpack.",
  "has a mirror.",
  "has a stapler.",
  "has a lock.",
  "has a broom.",
  "has a car.",
  "has a shovel.",
  "has a map.",
];
