const IMG_URL = "https://raw.githubusercontent.com/saramff/face-recognition-images/refs/heads/master/objects/"

export const correctObjects = [
  { sentence: "tiene una hucha.", img: `${IMG_URL}hucha.jpg`, correct: true },
  { sentence: "tiene una papelera.", img: `${IMG_URL}papelera.jpg`, correct: true },
  { sentence: "tiene una cuerda.", img: `${IMG_URL}cuerda.jpg`, correct: true },
  { sentence: "tiene una llave.", img: `${IMG_URL}llave.jpg`, correct: true },
  { sentence: "tiene un paraguas.", img: `${IMG_URL}paraguas.jpg`, correct: true },
  { sentence: "tiene unas gafas.", img: `${IMG_URL}gafas.jpg`, correct: true },
  { sentence: "tiene un plátano.", img: `${IMG_URL}platano.jpg`, correct: true },
  { sentence: "tiene una calculadora.", img: `${IMG_URL}calculadora.jpg`, correct: true },
  { sentence: "tiene unas tijeras.", img: `${IMG_URL}tijeras.jpg`, correct: true },
  { sentence: "tiene un peine.", img: `${IMG_URL}peine.jpg`, correct: true },
];

/*
  { sentence: "tiene una lupa.", img: `${IMG_URL}lupa.jpg`, correct: true },
  { sentence: "tiene una guitarra.", img: `${IMG_URL}guitarra.jpg`, correct: true },
  { sentence: "tiene miel.", img: `${IMG_URL}miel.jpg`, correct: true },
  { sentence: "tiene un micrófono.", img: `${IMG_URL}micrófono.jpg`, correct: true },
  { sentence: "tiene un martillo.", img: `${IMG_URL}martillo.jpg`, correct: true },
  { sentence: "tiene leche.", img: `${IMG_URL}leche.jpg`, correct: true },
  { sentence: "tiene un huevo.", img: `${IMG_URL}huevo.jpg`, correct: true },
  { sentence: "tiene un perro.", img: `${IMG_URL}perro.jpg`, correct: true },
  { sentence: "tiene una naranja.", img: `${IMG_URL}naranja.jpg`, correct: true },
  { sentence: "tiene un pan.", img: `${IMG_URL}pan.jpg`, correct: true },
  { sentence: "tiene una bicicleta.", img: `${IMG_URL}bicicleta.jpg`, correct: true },
  { sentence: "tiene café.", img: `${IMG_URL}café.jpg`, correct: true },
  { sentence: "tiene un globo.", img: `${IMG_URL}globo.jpg`, correct: true },
  { sentence: "tiene una pizza.", img: `${IMG_URL}pizza.jpg`, correct: true },
  { sentence: "tiene una piña.", img: `${IMG_URL}piña.jpg`, correct: true },
  { sentence: "tiene un ordenador.", img: `${IMG_URL}ordenador.jpg`, correct: true },
  { sentence: "tiene una pelota.", img: `${IMG_URL}pelota.jpg`, correct: true },
  { sentence: "tiene una mariposa.", img: `${IMG_URL}mariposa.jpg`, correct: true },
  { sentence: "tiene chocolate.", img: `${IMG_URL}chocolate.jpg`, correct: true },
  { sentence: "tiene una moneda.", img: `${IMG_URL}moneda.jpg`, correct: true },
  { sentence: "tiene un lápiz.", img: `${IMG_URL}lápiz.jpg`, correct: true },
  { sentence: "tiene una silla.", img: `${IMG_URL}silla.jpg`, correct: true },
  { sentence: "tiene un cinturón.", img: `${IMG_URL}cinturón.jpg`, correct: true },
  { sentence: "tiene una cuchara.", img: `${IMG_URL}cuchara.jpg`, correct: true },
  { sentence: "tiene un sombrero.", img: `${IMG_URL}sombrero.jpg`, correct: true },
  { sentence: "tiene queso.", img: `${IMG_URL}queso.jpg`, correct: true },
  { sentence: "tiene una maceta.", img: `${IMG_URL}maceta.jpg`, correct: true },
  { sentence: "tiene un batido.", img: `${IMG_URL}batido.jpg`, correct: true },
  { sentence: "tiene una flor.", img: `${IMG_URL}flor.jpg`, correct: true },
  { sentence: "tiene un reloj.", img: `${IMG_URL}reloj.jpg`, correct: true },
  { sentence: "tiene un tomate.", img: `${IMG_URL}tomate.jpg`, correct: true },
  { sentence: "tiene una calabaza.", img: `${IMG_URL}calabaza.jpg`, correct: true },
  { sentence: "tiene un dado.", img: `${IMG_URL}dado.jpg`, correct: true },
  { sentence: "tiene una regadera.", img: `${IMG_URL}regadera.jpg`, correct: true },
  { sentence: "tiene una libreta.", img: `${IMG_URL}libreta.jpg`, correct: true },
  { sentence: "tiene una manzana.", img: `${IMG_URL}manzana.jpg`, correct: true },
  { sentence: "tiene una regla.", img: `${IMG_URL}regla.jpg`, correct: true },
];

*/

export const incorrectObjects = [
  "tiene una lámpara.",
  "tiene una alfombra.",
  "tiene una nevera.",
  "tiene una sartén.",
  "tiene una almohada.",
  "tiene una jaula.",
  "tiene una escalera.",
  "tiene un bastón.",
  "tiene una botella.",
  "tiene un ventilador.",
  "tiene una maleta.",
  "tiene una impresora.",
  "tiene una cartera.",
  "tiene una linterna.",
  "tiene una corbata.",
  "tiene una plancha.",
  "tiene un casco.",
  "tiene una mochila.",
  "tiene un espejo.",
  "tiene una grapadora.",
  "tiene un candado.",
  "tiene una escoba.",
  "tiene un coche.",
  "tiene una pala.",
  "tiene un mapa.",
];
